# The URL the site will be built for
base_url = "https://docs.conforma.nz"
description = "Conforma is an open source workflow platform designed by The mSupply Foundation"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
build_search_index = true

theme = "adidoks"

[languages.en]
title="Conforma"
build_search_index = true

[languages.en.translations]
flag="🇬🇧"
TOCtitle="On this page"
search_placeholder = "Search docs..."

[languages.es.translations]
summary = "Mi blog"
title = "Conforma.es"
flag="🇪🇸"
TOCtitle="En esta pagina"
search_placeholder = "Buscar documentos..."

[languages.es]
build_search_index = true
title="Conforma 🇪🇸"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[extra]
# Put all your custom variables here

# Set theme-color meta tag for Chrome browser
theme_color = "#45818e"

# Set HTML file language
language_code = "en-US"

# More about site's title
title_separator = "-"  # set as |, -, _, etc
#itle_addition = "Open mSupply... Health Supply Chain Management for the World"

# Set date format in blog publish metadata
timeformat = "%B %e, %Y" # e.g. June 14, 2021
timezone = "America/New_York"

# Github repo for the edit button on pages...
edit_page = false
docs_repo = "https://github.com/openmsupply/mSupply_docs"
repo_branch = "main"

# Menu items


